config/routes.rb
Rails.application.routes.draw do
  # resources :storages, :uploaded_files
  resources :storages do
    resources :uploaded_files do
      member do
        get :download_file
      end
    end
  end

  # due to the use of the custom regitration controller we had to define the new registration path for devise
  devise_for :users, path: 'user', controllers: {
      :registrations => "users/registrations" }

  root :to =>'pages#index'
  
  # share file with others 
  post 'share_file' => 'uploaded_files#share_file'
  # user clicks on the received URL with the uniquie_url in path and to search a file with the unique_url
  # endpoint to securley download files for not their owner.
  get 'download_shared_file/:unique_url' => 'uploaded_files#download_shared_file'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/uploaded_file.rb
class UploadedFile < ApplicationRecord
  belongs_to :storages, optional: true
  validates :name, presence: true
  # mount cariervawes ImageUploader
  mount_uploader :image, ImageUploader
  require 'securerandom'

  def set_self
    # using SecureRandom to generate unique uuid for file path
    self[:unique_url] = SecureRandom.uuid
    self[:size] = image.size
    self[:name] = image.filename
  end

end

app/controllers/uploaded_files_controller.rb
require 'observer'
class UploadedFilesController < ApplicationController
  include Observable
  before_action :observer, only: [:share_file]
  before_action :get_storage, except: [:download_shared_file, :share_file]
  before_action :set_uploaded_file, only: [:show, :edit, :update, :destroy]

  # GET /uploaded_files
  # GET /uploaded_files.json
  def index
    if !@storage.nil?
      @uploaded_files = @storage.uploaded_files
    else
      flash[:error] = "Storages or Files do not exist, or you do not have permission to access"
      redirect_to root_path
    end
  end

  # GET /uploaded_files/1
  # GET /uploaded_files/1.json
  def show
    if @uploaded_file.nil?
      flash[:error] = "File does not exist, or you do not have permission to access"
      redirect_to root_path
    end
  end

  # GET /uploaded_files/new
  def new
    @uploaded_file = @storage.uploaded_files.build
  end

  # GET /uploaded_files/1/edit
  def edit
  end

  # POST /uploaded_files
  # POST /uploaded_files.json
  def create
    @uploaded_file = @storage.uploaded_files.build(uploaded_file_params)
    @uploaded_file.set_self

    # get the filename and the size from the uploaded file parameters
    name = params[:uploaded_file][:image].original_filename
    size = :image.size

    respond_to do |format|
      # validate file with our custom gem that checks name, extension and size
      if RailsValidator.validate_file( name, size) && @uploaded_file.save
        update_storage_size

        format.html { redirect_to storage_uploaded_files_path(@storage), notice: 'Uploaded file was successfully created.' }
        format.json { render :show, status: :created, location: @uploaded_file }
      else
        flash[:error] = "Invalid file format"
        format.html { render :new }
        format.json { render json: @uploaded_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploaded_files/1
  # DELETE /uploaded_files/1.json
  def destroy
    @uploaded_file.destroy
    respond_to do |format|
      update_storage_size
      
      format.html { redirect_to storage_uploaded_files_path(@storage), notice: 'Uploaded file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download_file
    set_uploaded_file
    file = @uploaded_file.image

    if file.try(:file).exists?
      data = open(file.url)
      send_data data.read, type: data.content_type, x_sendfile: true, :filename => @uploaded_file.name
    else
      respond_to do |format|
        flash[:error]= "We're sorry, we could not download that file!"
        format.html { redirect_to root_path }
        format.json { head :no_content }
      end
    end
  end

  def download_shared_file
    # foind the uploaded file with the unique_url
    @uploaded_file = UploadedFile.find_by_unique_url(params[:unique_url])

    respond_to do |format|      
      if @uploaded_file
        # associate file with the imagesaved to the database
        file = @uploaded_file.image
        if file.try(:file).exists?
          # if the file exists, we open it with the url. This returns a File object, so
          # we are able to call functions on it as read
          data = open(file.url)
          # uses X-SendFile to send the file when set to true
          # Since it is using the webserver to send files, it may lower memory consumtion on the server
          # and may not block the application for further requests
          send_data data.read, type: data.content_type, x_sendfile: true, :filename => @uploaded_file.name
          return
        else
          flash[:error]= "We're sorry, we could not download that file!"
          format.html { redirect_to root_path }
          format.json { head :no_content }
        end
      else
        flash[:error]= "We're sorry, that file does not exist!"
        format.html { redirect_to root_path }
        format.json { head :no_content }
      end
    end
  end

  def share_file
    # find storage by storage_id and find file by uploaded_file_id
    @storage = Storage.find_by_id(params[:storage_id])
    @uploaded_file = @storage.uploaded_files.find_by_id(params[:uploaded_file_id])
    # take email as a param from the view
    @email = params[:email]
    # define current user with Devise's built in current_user
    @current_user = current_user

    respond_to do |format|
      # validate email and file with our custom gem
      if RailsValidator.validate_email(@email) && RailsValidator.validate_file(@uploaded_file.name, @uploaded_file.size)
        # set changed flag to true otherwise notification won't be sent
        changed
        # notify observer and pass the email where we want the email to be sent, the current user and the url that can be clicked
        notify_observers(@email, @current_user, @uploaded_file.unique_url)
        # redirect and show success message
        format.html { redirect_to storage_uploaded_file_path(id: params[:uploaded_file_id], storage_id: params[:storage_id]), notice: 'Email sent successfully' }
        format.json { render :show, status: :created, location: @uploaded_file }
      else
        # flash error and redirect
        flash[:error] = "Invalid email, please try again!"
        format.html { redirect_to storage_uploaded_file_path(id: params[:uploaded_file_id], storage_id: params[:storage_id]), error: 'Invalid email' }
      end
    end
  end

  private

    def observer
      add_observer(EmailNotifier.new)
    end

    def update_storage_size
      @storage.set_size
      @storage.save
    end

    def get_storage
      # find storage by the logged in user_id and storage_id to prevent unaythorised access to storages
      @storage = Storage.find_by(user_id: current_user.id, id: params[:storage_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_uploaded_file

      if !@storage.nil?
        @uploaded_file = @storage.uploaded_files.find_by_id(params[:id])
      else
        flash[:error] = "File does not exist, or you do not have permission to access"
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uploaded_file_params
      params.require(:uploaded_file).permit(:name, :image, :share_id, :unique_url)
    end
end

app/helpers/uploaded_files_helper.rb
module UploadedFilesHelper
end

app/views/uploaded_files/_form.html.erb
<%= form_for ([@storage, uploaded_file]) do |f| %>
  <br>
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-sm-12">
        <p class="text_input_fields storage_input" ><%= f.file_field :image %></p>
      </div>
      <div class="col-lg-2 col-sm-12">
        <%= f.submit "Upload" %>
      </div>
    </div>
  </div>
<% end %>

app/views/uploaded_files/edit.html.erb
<%= form_for ([@storage, @uploaded_file]) do |f| %>
  <br>
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-sm-12">
        <% text_field :email, :class => "text_input_fields storage_input", :type => "email", :placeholder=>"enter email"%>
        <input class = "text_input_fields storage_input", type = "email", placeholder="enter email"%>
      </div>
      <div class="col-lg-2 col-sm-12">
        <%= f.submit "Share" %>
      </div>
    </div>
  </div>
<% end %>

app/views/uploaded_files/index.html.erb
<div class="breadcrumbs">
  <%= link_to 'home', root_path %> >> <%= link_to 'storages', storages_path %> >> <%= @storage.name %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>File Name</th>
      <th>File Size</th>
      <th>Created At</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @uploaded_files.each do |uploaded_file| %>
      <tr>
        <td><%= uploaded_file.name %></td>
        <td><%= (uploaded_file.size / (1024.0 * 1024.0)).round(2)  %> MB</td>
        <td><%= uploaded_file.created_at.strftime("%F") %></td>
        <td><%= link_to 'Preview', [@storage, uploaded_file]%></td>
        <td><%= link_to 'Delete', [@storage, uploaded_file], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Upload File", new_storage_uploaded_file_path(@storage), :class=>"buttonLink btn-sm float-right" %>

app/views/uploaded_files/new.html.erb
<div class="breadcrumbs">
  <%= link_to 'home', root_path %> / <%= link_to 'storages', storages_path %> / <%= link_to @storage.name, storage_uploaded_files_path(@storage) %>
</div>
<%= render 'form', uploaded_file: @uploaded_file %>

app/views/uploaded_files/show.html.erb
<div class="breadcrumbs">
  <%= link_to 'home', root_path %> >> <%= link_to 'storages', storages_path %> >> <%= link_to @storage.name, storage_uploaded_files_path(@storage) %> >> <%= @uploaded_file.name %>
</div>

<div class="container">
  <div class="row">
    <br><br>
  </div>
  <div class="row">
    <div class="image-thumb col-sm">
      <%= image_tag(@uploaded_file.image_url(:thumb).to_s, class:"img-responsive", :alt => "no image available") if  @uploaded_file.image?  %>
    </div>
    <div class="col-sm">
      <table class="table table-hover">
        <tbody>
        <tr>
          <th>File Name</th>
          <td><%= @uploaded_file.name %></td>
        </tr>
        <tr>
          <th>Uploaded at</th>
          <td><%= @uploaded_file.created_at.strftime("%F") %></td>
        </tr>
        <tr>
          <th>File size</th>
          <td><%= (@uploaded_file.size / (1024.0 * 1024.0)).round(2) %> MB</td>
        </tr>
        </tbody>
      </table>
      <%= link_to 'Download', download_file_storage_uploaded_file_path(@storage) , :class=>"buttonLink btn-sm"%>
    </div>
  </div>
</div>
<h2>Share Your File</h2>
  <%= form_tag (share_file_path) do %>
    <%= text_field_tag(:email, value = nil, options = {placeholder: "share@with.me", class: "text_input_fields uploadedFileView "})%>
    <%= hidden_field_tag :storage_id, @storage.id %>
    <%= hidden_field_tag :uploaded_file_id, @uploaded_file.id %>
    <%= submit_tag "Share" %>
  <% end %>