config/routes.rb
Rails.application.routes.draw do
  # resources :storages, :uploaded_files
  resources :storages do
    resources :uploaded_files do
      member do
        get :download_file
      end
    end
  end

  # due to the use of the custom regitration controller we had to define the new registration path for devise
  devise_for :users, path: 'user', controllers: {
      :registrations => "users/registrations" }

  root :to =>'pages#index'
  
  # share file with others 
  post 'share_file' => 'uploaded_files#share_file'
  # user clicks on the received URL with the uniquie_url in path and to search a file with the unique_url
  # endpoint to securley download files for not their owner.
  get 'download_shared_file/:unique_url' => 'uploaded_files#download_shared_file'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/storage.rb
class Storage < ApplicationRecord
  belongs_to :users,  optional: true
  has_many :uploaded_files, dependent: :destroy
  validates :name, presence: true

  def set_size
    self[:size] = calculate_storage_size
  end

  # iterating through on the uploaded files  in a storage and adding up their sizes to calculate storage size
  # returns a decimal number 
  def calculate_storage_size
    storage_size = 0;
    if self.uploaded_files
      self.uploaded_files.each do |file|
        storage_size += file.size
      end
    end
    return storage_size
  end
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  before_action :get_user
  before_action :set_storage, only: [:show, :edit, :update, :destroy]

  # GET /storages
  # GET /storages.json
  def index
    @storages = @user.storages
  end

  # GET /storages/1
  # GET /storages/1.json
  def show
    if @storage.nil?
      flash[:error] = "Storage does not exist, or you do not have permission to access"
      redirect_to root_path
    end
  end

  # GET /storages/new
  def new
    @storage = Storage.new
  end

  # GET /storages/1/edit
  def edit
  end

  # POST /storages
  # POST /storages.json
  def create
    @storage = Storage.new(storage_params)
    respond_to do |format|
      if @storage.save
        # binding storage to user
        @user.storages << @storage
        format.html { redirect_to @storage, notice: 'Storage was successfully created.' }
        format.json { render :show, status: :created, location: @storage }
      else
        format.html { render :new }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storages/1
  # PATCH/PUT /storages/1.json
  def update
    respond_to do |format|
      if @storage.update(storage_params)
        format.html { redirect_to @storage, notice: 'Storage was successfully updated.' }
        format.json { render :show, status: :ok, location: @storage }
      else
        format.html { render :edit }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storages/1
  # DELETE /storages/1.json
  def destroy
    @storage.destroy
    respond_to do |format|
      format.html { redirect_to storages_url, notice: 'Storage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_user
      @user = User.find(current_user.id)
    end

    # Use callbacks to share common setup or constraints between actions.
    # Find storage by users => this way only the owner of the storage will see the storages and the files in them.
    def set_storage
      @storage = Storage.find_by(user_id: @user.id, id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def storage_params
      params.require(:storage).permit(:size, :name)
    end
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/views/storages/_form.html.erb
<%= form_for(storage) do |f| %>
  <% if storage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(storage.errors.count, "error") %> prohibited this storage from being saved:</h2>
      <ul>
      <% storage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="container">
      <div class="row">
        <div class="col-lg-10 col-sm-12">
          <%= f.text_field :name, :class=> "text_input_fields storage_input ", :placeholder=>"New Storage Name" %>
        </div>
        <div class="col-lg-2 col-sm-12">
          <%= f.submit%>
      </div>
      </div>
    </div>
  </div>
<% end %>

app/views/storages/edit.html.erb
<h1>Editing Storage</h1>

<%= render 'form', storage: @storage %>

<%= link_to 'Show', @storage %> |
<%= link_to 'Back', storages_path %>
<hr>
<%= link_to "Close", root_path %>

app/views/storages/index.html.erb
<div class="breadcrumbs">
  <%= link_to 'home', root_path %> >> storages
</div>
<h2>My Storages</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th class="th-sm">Storage Name</th>
      <th class="th-sm">Storage Size</th>
      <th class="th-sm">Created At</th>
      <th class="th-sm" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @storages.each do |storage| %>
      <tr>
        <td><%= storage.name %></td>
        <td><%= storage.size %></td>
        <td><%= storage.created_at.strftime("%F")%></td>
        <td><%= link_to 'Open', storage_uploaded_files_path(storage.id).to_s %></td>
        <td><%= link_to 'Delete', storage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="field">
  <%= link_to 'New Storage', new_storage_path, :class=>"buttonLink float-right"%>
</div>

app/views/storages/new.html.erb
<div class="breadcrumbs">
  <%= link_to 'home', root_path %> >> <%= link_to 'storages', storages_path %> >> New Storage
</div>

<%= render 'form', storage: @storage %>

app/views/storages/show.html.erb
<div class="breadcrumbs">
  <%= link_to 'home', root_path %> >> <%= link_to 'my storages', storages_path %> >> <%= @storage.name %>
</div>

  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-sm-12">
        <p class="text_input_fields storage_input" >Add file to <%= @storage.name %> storage</p>
      </div>
      <div class="col-lg-2 col-sm-12">
        <%= link_to "Add File", new_storage_uploaded_file_path(@storage), :class=>"buttonLink"%>
      </div>
    </div>
  </div>