config/routes.rb
Rails.application.routes.draw do
  # resources :storages, :uploaded_files
  resources :storages do
    resources :uploaded_files do
      member do
        get :download_file
      end
    end
  end

  # due to the use of the custom regitration controller we had to define the new registration path for devise
  devise_for :users, path: 'user', controllers: {
      :registrations => "users/registrations" }

  root :to =>'pages#index'
  
  # share file with others 
  post 'share_file' => 'uploaded_files#share_file'
  # user clicks on the received URL with the uniquie_url in path and to search a file with the unique_url
  # endpoint to securley download files for not their owner.
  get 'download_shared_file/:unique_url' => 'uploaded_files#download_shared_file'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer id='footer'>
    &copy;<%= Time.now.year %> Cloud Storage
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="header">
  <%= link_to image_tag('logo.png'), root_path, :class => "logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item nav-link">
          <%= link_to 'My Storages  |', storages_path%>
        </li>
        <li class="nav-item nav-link">
        <%= link_to 'Edit Profile  |', edit_user_registration_path%>
        </li>
        <li class="nav-item nav-link">
          <%= link_to "DELETE ACCOUNT  |", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to 'Sign Out ', destroy_user_session_path, :method =>:delete %>
        </li>
      <% else %>
        <li class="nav-item nav-link">
          <%= link_to 'Register', new_user_registration_path %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to 'Sign In', new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_profile.html.erb
<div class="float-right">
  <% if current_user.admin %>
    <h2>Hello admin</h2>
  <% else %>
    <h2>Hello <%= current_user.email %>&nbsp; &nbsp;<%= image_tag("user.png", :alt => "user pic", :id=> "profile_image")%></h2>
  <% end %>
</div>

app/views/layouts/_subscribe_buttons.html.erb
<% unless user_signed_in? %>
  <a href="/user/sign_up">
    <input class="btn" type="submit" value="subscribe">
  </a>
<% else %>
  <a href="/user/edit">
    <input class="btn" type="submit" value="subscribe">
  </a>
<% end %>

app/views/layouts/_subscriptions.html.erb
<section class="pricing py-5">
  <div class="container">
    <div class="row">
      <!-- Free Tier -->
      <% if !user_signed_in? || current_user.selected_package != 5%>
      <div class="col-lg-4">
        <div class="card mb-5 mb-lg-0">
          <div class="card-body">
            <h5 class="card-title text-muted text-uppercase text-center">Free</h5>
            <h6 class="card-price text-center">€0<span class="period"> /month</span></h6>
            <hr>
            <ul class="fa-ul">
              <li>5GB Storage</li>
              <li>Unlimited File Share</li>
              <li>Community Access</li>
            </ul>
            <%= render 'layouts/subscribe_buttons'%>
          </div>
        </div>
      </div>
      <% end %>
      <!-- Plus Tier -->
      <% if !user_signed_in? || current_user.selected_package != 25%>
      <div class="col-lg-4">
        <div class="card mb-5 mb-lg-0">
          <div class="card-body">
            <h5 class="card-title text-muted text-uppercase text-center">Plus</h5>
            <h6 class="card-price text-center">€9<span class="period"> /month</span></h6>
            <hr>
            <ul class="fa-ul">
              <li></span>25GB Storage</li>
              <li>Unlimited File Share</li>
              <li>Community Access</li>
            </ul>
            <%= render 'layouts/subscribe_buttons'%>
          </div>
        </div>
      </div>
      <% end %>
      <!-- Extra Tier -->
      <% if !user_signed_in? || current_user.selected_package != 50%>
      <div class="col-lg-4">
          <div class="card mb-5 mb-lg-0">
            <div class="card-body">
              <h5 class="card-title text-muted text-uppercase text-center">Extra</h5>
              <h6 class="card-price text-center">€12<span class="period"> /month</span></h6>
              <hr>
              <ul class="fa-ul">
                <li></span>50GB Storage</li>
                <li>Unlimited File Share</li>
                <li>Community Access</li>
              </ul>
              <%= render 'layouts/subscribe_buttons'%>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cloud Storage</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>
  </head>

  <body class='container-fluid' >
    <%= render 'layouts/header' %>
    <div class="wrapper">
      <% if current_page?('/')  %>
        <div class="loggedInSection">
          <%= render 'layouts/messages'%>
          <%= yield %>
        </div>
      <% elsif current_page?('/user/edit') || !user_signed_in?%>
        <div class="new_user_modal">
          <%= render 'layouts/messages'%>
          <%= yield %>
        </div>
      <% else %>
      <div class="loggedInSection">
        <%= render 'layouts/messages'%>
        <%= yield %>
      </div>
      <% end %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/file_shared_notification.html.erb
<h1>Hi <%= @email %></h1>
<p> <%= @current_user.email %> just shared a file with you</p>
<p>Download it <a href="https://www.ncicloud.live:/download_shared_file/<%= @unique_url %>">here</a></p>